import 'package:hive/hive.dart';

part 'userdata_model.g.dart'; // This file will be generated by the Hive code generator

@HiveType(typeId: 0)
class UserModel extends HiveObject {
  @HiveField(0)
  String firstName;

  @HiveField(1)
  String lastName;

  @HiveField(2)
  String email;

  @HiveField(3)
  String password;

  UserModel({required this.firstName, required this.lastName, required this.email, required this.password});
}
